SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Author] (

    [Id][int] IDENTITY(1, 1) NOT NULL,

    [Name] [nvarchar] (50) NOT NULL,

    [Surname] [nvarchar] (50) NULL,
PRIMARY KEY CLUSTERED 
(

    [Id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON[PRIMARY]
) ON[PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Post] (

    [Id][int] IDENTITY(1, 1) NOT NULL,

    [Title] [nvarchar] (50) NULL,
	[Description][nvarchar] (150) NULL,
	[AuthorId][int] NOT NULL,

    [Content] [nvarchar] (max)NULL,
PRIMARY KEY CLUSTERED 
(

    [Id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON[PRIMARY]
) ON[PRIMARY] TEXTIMAGE_ON[PRIMARY]
GO
ALTER TABLE [dbo].[Post] WITH CHECK ADD  CONSTRAINT [FK_Post_Author] FOREIGN KEY([AuthorId])
REFERENCES[dbo].[Author]([Id])
GO
ALTER TABLE [dbo].[Post] CHECK CONSTRAINT[FK_Post_Author]
GO
